#!/usr/bin/python3
from linecache import getline
from sys import argv


def first_factor(n: int) -> int:
    if n <= 3:
        return (1)
    if n % 2 == 0:
        return (2)
    if n % 3 == 0:
        return (3)
    limit = int(n ** 0.5)
    if limit % 2 == 0:
        limit += 1
    i, j = 5, limit
    while i <= j:
        if n % i == 0:
            return (i)
        if n % j == 0:
            return (j)
        i += 1
        j -= 1
    return (1)


if __name__ == "__main__":
    line = 1
    while True:
        line_s = getline(argv[1], line)
        if (len(line_s) == 0):
            break
        num = int(line_s[:-1])
        factor = first_factor(num)
        print("{}={}*{}".format(num, num // factor, factor))
        line += 1
